[project]
name = "aepsych-config-builder"
version = "0.0.1"
description = "Config builder utilities for AEPsych extension"
authors = [ { name = "AEPsych Contributors" } ]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0"