[workspace]
channels = ["conda-forge"]
preview = ["pixi-build"]
name = "aepsych-cpu"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
loguru = ">=0.7.3,<0.8"
pytest = ">=9.0.2,<10"
git-filter-repo = ">=2.38.0,<3"
