[project]
name = "aepsych-custom-mean"
version = "0.0.1"
description = "Custom mean functions for AEPsych extension"
authors = [ { name = "AEPsych Contributors" } ]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0"