[project]
name = "aepsych-custom-generators"
version = "0.0.1"
description = "Custom generator implementations for AEPsych extension"
authors = [ { name = "AEPsych Contributors" } ]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0"